"""empty message

Revision ID: 3b17c5acf924
Revises: 61e5ee81c5d9
Create Date: 2021-08-10 09:00:34.117239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b17c5acf924'
down_revision = '61e5ee81c5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_hours',
    sa.Column('Employee ID', sa.Integer(), nullable=False),
    sa.Column('Billable Rare (per hour)', sa.Integer(), nullable=False),
    sa.Column('Company', sa.String(length=60), nullable=False),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Start Time', sa.Time(), nullable=True),
    sa.Column('End Time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('Employee ID', 'Company')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_hours')
    # ### end Alembic commands ###
