"""empty message

Revision ID: 5233e4748032
Revises: 
Create Date: 2021-08-17 08:43:42.630788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5233e4748032'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_db',
    sa.Column('Employee ID', sa.Integer(), nullable=False),
    sa.Column('Billable Rate (per hour)', sa.Integer(), nullable=False),
    sa.Column('Company', sa.String(length=60), nullable=False),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('Start Time', sa.Time(), nullable=True),
    sa.Column('End Time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('Employee ID', 'Company')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_db')
    # ### end Alembic commands ###
