"""empty message

Revision ID: 61e5ee81c5d9
Revises: 
Create Date: 2021-08-10 08:28:23.584230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61e5ee81c5d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('recordID', sa.Integer(), nullable=False),
    sa.Column('employeeID', sa.Integer(), nullable=False),
    sa.Column('billableRate', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('startTime', sa.Text(), nullable=False),
    sa.Column('endTime', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('recordID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
